feat:
  - head-branch: ['^feat']

fix:
  - head-branch: ['^fix']

refactor:
  - head-branch: ['^refactor']

chore:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - '**/*/package.json'
