import * as stylex from "@stylexjs/stylex";
import type { Metadata } from "next";
import globalStylex from "~/styles/globals.stylex";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body {...stylex.props(globalStylex.global)}>{children}</body>
    </html>
  );
}
