name: Continuous Deployment

on:
  push:
    branches: [dev]
    paths: ['packages/web/**', 'packages/back-office/**']

jobs:
  Continous-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ secrets.SOURCE_GITHUB_URL }}
          source_branch: ${GITHUB_REF_NAME}
          destination_repo: ${{ secrets.DESTINATION_GITHUB_URL }}
          destination_branch: ${GITHUB_REF_NAME}
